version: "3.5"

services:
  db:
    image: postgres:${POSTGRES_ver}
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      TZ: ${TimeZone}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
     - "postgres-data:/var/lib/postgresql/data"
     #- "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
     - ./postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8083:8083"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      db:
        condition: service_healthy
     

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      PORT: 3003
      PROXY_API: backend:8083/
    ports:
      - "3003:3003"
    depends_on:
      - backend

  adminer:
    container_name: adminer
    image: adminer:${ADMINER_ver}
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres-data:
