# Use postgres/example user/password credentials
version: '3.3'

services:
  backend:
    container_name: backend
    build: backend
    depends_on:
      postgres-database:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
    command: "postgres -c listen_addresses=localhost"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 20s
      retries: 50

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080